dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: ltUcaBAoA+RISq51crndzrTmkmwON2HUgf7HDC8Oz8CUOC56Z7oQYKJsIFwLT8CGgsRYCpK7yPfVRKvThi4eFFFY707TIJyXyuD75lwj/hbexyOPgoEc6KIuyyTYhldihjwf7jjrD1GHjUzjJOI7x+ll+bPBMIM79baf1OBG/TtUnA2QHpzaVBLZq3nl3oEpWu3K4ieUITXaNaZud0WH1lnUmA6TFgOML0JfwiWoI8G6UDDJZcbf7616jfMt0AlAArbDp5wmUK/9GRiDKzWxqfupz4bn6FPCm67ZY2OpxY73IWrcySX6Ew6dkrzyEtg+Zg46mzhAUKWbogWCVoumaRMWoNvikdVjpOUrzqrumMiV/0BjuhzmZoh4ukiQw5sgrd5eC68Clc6Y+2viKj+l7Bu4OKJmnXCpXN2Cws3E5KvYBBw6pe8cJiPDA+51FQaK6XnQE32oW4059k436eTBcjMLaCKOP1uybmiU229eEYC3H82y05Czq/exAwgaZtj9ecsicCCvMBgm0ilvWFuYn173wQVegHCYL5bTGtYYrft5GoReLTpWG5Z+bIqI7igWjvjQr6K4uSxug5nFZjIgWPXZI6VV0RsEgt16Sfj+xCVWW6zdQp1UAVzA0yy3vKBPgcxW1wKBQTLuyBrIrohvH2gqbIxx0wcq1bGgZ0yQxSM=
